### ISSUE TITLE
Use separate icons for test failures and other errors

### ISSUE THREAD

**Issue by mhmdkzr** [DudeNr33/vscode-pythonautotest#2]
Currently the red icon in status bar is shown when tests don't pass and when there is another error e.g. compiler error. I'm not sure if this is technically possible, but it would be great if they could had separate icons, so the developer could instantly know if it was the tests that didn't pass, or if there was another problem, without checking the terminal.

**Comment by DudeNr33** [comment]
I decide which icon to display based on the exit code. If whatever tool you are using for your tests uses different exit codes for different outcomes (e.g. 0 = all tests passed, 1 = tests failed, 2 = compiler error), then it would be possible to let the user define a mapping of exit code to the icon to display.

Would that be an option for you?

**Comment by mhmdkzr** [comment]
I checked exit codes for Elixir (with ExUnit), exit code of failed tests is 2 and exit code of compiler errors is 1. But I don't know if other testing tools behave similarly, so, I think it would be nice to have this as an option, disabled by default to keep things simple. If a user was interested, he/she can enable it and set a custom icon or icon color based on the exit code.

**Comment by DudeNr33** [comment]
I created a PR for this (#3). If you like you can take a look and give feedback. No worries if you don't have the time for it, in that case I will just merge it in the next few days and release a new version.

**Comment by mhmdkzr** [comment]
It looks great! Thank you :)

**Comment by DudeNr33** [comment]
V1.1.0 is now available from the marketplace. :)
